### ISSUE TITLE
Mapping between 'id' and 'series_id'

### ISSUE THREAD

**Issue by ndominguez4219** [avelkoski/FRB#3]
Is there a mapping between 'id' (an integer) and 'series_id' (a string) ?  Some functions require one or the other.  Thank you.

**Comment by avelkoski** [comment]
Not exactly. FRED offers various identification numbers, and each number has a particular purpose. In some cases, a relationship exists among identification numbers. For instance, series are associated to categories, so the string identification number assigned to a series may be mapped to the integer identification number of its parent category. However, you definitely cannot use the integer identification number for a category in a function that's built to query a series. That's just how the API works.
